dist: focal
language: java
before_install:
  - curl -L "http://nusmv.fbk.eu/distrib/NuSMV-2.6.0-zchaff-linux64.tar.gz" | tar --extract --gzip --strip-components=2 -C $HOME/bin "NuSMV-2.6.0-Linux/bin/NuSMV" || true
  - curl -N -L "http://es-static.fbk.eu/tools/nuxmv/downloads/nuXmv-2.0.0-linux64.tar.gz" | tar --extract --gzip --strip-components=2 -C $HOME/bin "nuXmv-2.0.0-Linux/bin/nuXmv" || true
install: 
  - "gradle --version"
script: gradle --no-daemon -DGRADLE_OPTS="-Xms128m" --stacktrace build --debug
cache:
  directories:
  - "$HOME/.gradle"
  - "$HOME/bin"
